jenkinsci/pipeline-build-step-plugin

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-wait.html

Build's step documentation incorrectly describe "FAILED", instead of "FAILURE", as one of the valid build results.

[FIX JENKINS-37484] Replace FAILED with FAILURE

---

pom.xml
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

Otherwise you get
```
java.lang.NoSuchMethodError: jenkins.scm.impl.mock.MockSCMController.createRepository(Ljava/lang/String;)V
at org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerStepTest.triggerOrgFolder(BuildTriggerStepTest.java:391)
```
due to incompatible changes in `scm-api` tests.
@reviewbybees

Minor updates for better PCT compatibility

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/DownstreamFailureCause.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/DownstreamFailureCause/summary.jelly
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

[JENKINS-49073](https://issues.jenkins-ci.org/browse/JENKINS-49073)
Probably improved by https://github.com/jenkinsci/workflow-step-api-plugin/pull/44.
Note that this may also satisfy the stated use case for #13:
> this information can be used by Build Failure Analyzer Plugin to show failures in child jobs on the top trigger job

[JENKINS-49073] Propagate the downstream result, not just FAILURE

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

It looks like tests pass and the snippet generator works correctly even without this override, so I'm not sure what it's for. If it turns out it is necessary, I'd like to add a test and/comment explaining what it is here for.
EDIT: In the end, just migrating some tests from workflow-cps, see https://github.com/jenkinsci/workflow-cps-plugin/pull/304.

Migrate snippet generator tests from workflow-cps

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

While looking at the test suite for this plugin, I noticed the `CpsFlowDefinition`s in the tests don't consistently use the script security sandbox. Using the script security sandbox results in a more realistic environment given that the script security sandbox should always be enabled in production.
In this change, I replaced any usages of the deprecated single-argument constructor for `CpsFlowDefinition` with usages of the non-deprecated two-argument constructor, passing in `true` as the second argument in order to always enable the script security sandbox.

Consistently use sandbox for CpsFlowDefinitions

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/Messages.properties
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

See [JENKINS-60216](https://issues.jenkins-ci.org/browse/JENKINS-60216). Subsumes #34. 
Tries to keep the behavior as similar to https://github.com/jenkinsci/parameterized-trigger-plugin/pull/62 as possible, since that behavior has been around for a long time so it seems unlikely to be problematic (there was a [followup commit](https://github.com/jenkinsci/parameterized-trigger-plugin/commit/8f410be6a8a203e92c4120a12750514878585869) for some issues, but from reading the PR and associated tickets, it seems that case only applied to Choice Parameters, which are already special-cased here and will not be converted by this PR).
I'll create a JIRA ticket for this tomorrow for tracking.
@Wadeck: I added you as a co-author to the commit because it is based on a squashed version of your PR, but …

[JENKINS-60216] Make the build step automatically convert some kinds of parameter mismatches

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-propagate.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

#24 changed the behavior of this plugin to propagate the result of downstream builds. However, only propagation of unstable builds was covered in unit tests, and the documentation was not updated. This PR adds test coverage for the other types of downstream statuses and updates the documentation.

Test propagation of additional downstream result types

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java

In d5eb973, a TODO was added noting that the `ParameterizedJobMixIn.scheduleBuild2` convenience method introduced in jenkinsci/jenkins#1771 should be used once the baseline was 1.621 or higher. The baseline is now 2.121.1, so this TODO can be completed.
I verified that this code was exercised in `BuildTriggerStepTest#triggerWorkflow`.

Use ParameterizedJobMixIn.scheduleBuild2 convenience method

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java

In c869245 a TODO was added to use `removeAction` once the baseline was updated to a version with support for [JENKINS-39404](https://issues.jenkins-ci.org/browse/JENKINS-39404). That fix was released in 2.30 and the baseline is now 2.121.1, so this TODO can be completed.
I verified that this code was exercised in `BuildTriggerStepTest#triggerWorkflow`.

Use Actionable.removeActions

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

While perusing the source tree, I noticed a number of deprecated methods:
- The documentation for [`User.get(java.lang.String)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#get-java.lang.String-) states: "This method is deprecated, because it causes unexpected `User` creation by API usage code and causes performance degradation of used to retrieve users by ID. Use [`getById(java.lang.String, boolean)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#getById-java.lang.String-boolean-) when you know you have an ID."
- The documentation for [`Jenkins.getActiveInstance()`](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#getActiveInstance--) states: "This is a verbose historical alias for [`get()`](https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#get--)."
- …

Remove usages of deprecated APIs

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java

See [JENKINS-60354](https://issues.jenkins-ci.org/browse/JENKINS-60354) and https://github.com/jenkinsci/workflow-step-api-plugin/pull/51.

[JENKINS-60354] Mark that FlowInterruptedException is not used for actual interruption here

---

pom.xml

Bumps the [plugin parent POM](https://github.com/jenkinsci/plugin-pom) from 3.43 to 3.54.
See [the changelog](https://github.com/jenkinsci/plugin-pom/releases) and the full diff in [the compare view](https://github.com/jenkinsci/plugin-pom/compare/plugin-3.43...plugin-3.54).

 Bump plugin parent POM

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java

See [JENKINS-60779](https://issues.jenkins-ci.org/browse/JENKINS-60779).
Not sure about adding tests for this, I'd really prefer not to have a dependency on either of the relevant plugins, even in test scope.

[JENKINS-60779] Do not log conversion warnings for choice-like parameter definitions

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

See [JENKINS-62483](https://issues.jenkins-ci.org/browse/JENKINS-62483).
When the plugin processes the list of job parameters, it stores them in a randomly ordered map and passes on this map to the job being triggered. If a job has a large amount of parameters, this makes it more difficult for a user to look up a build's parameters. This PR ensures that parameters are always passed on in the order that the job defines.

JENKINS-62483: Maintain parameter list order

---

Jenkinsfile
README.md
pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-parameters.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

See [JENKINS-62305](https://issues.jenkins-ci.org/browse/JENKINS-62305).
https://github.com/jenkinsci/jenkins/pull/4630 changed the `@DataBoundConstructor` for `PasswordParameterValue` so that one of its parameters is a `Secret`, but `Secret` is not supported by data binding via `DescribableModel` in `structs`. 
This PR uses `CustomDescribableModel` to maintain compatibility with existing uses of the `build` step with password parameters, and adds documentation explaining that credentials should be preferred over password parameters going forward.
TODO: Do we want to add a runtime warning (e.g. message in the build log) any time a password parameter is used with the `build` step? My understanding is that while password parameters are not ideal, they are not completely broken, so I am a …

[JENKINS-62305] Make password parameters work with the build step in Jenkins 2.236+

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-wait.html

I added a missing online help for the wait argument 
https://issues.jenkins.io/browse/JENKINS-65324

[JENKINS-65324] added a missing online help

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildUpstreamCause.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

This is part of a bigger change for blueocean in order to fix downstream links.
* (master) https://github.com/jenkinsci/blueocean-plugin/pull/2187
* (backport on 1.24.x) https://github.com/jenkinsci/blueocean-plugin/pull/2188

[JENKINS-60995] Implement a specific UpstreamCause class containing the nodeId that triggered the build

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepRestartTest.java

We seem to be generally preferring `JenkinsSessionRule` to `RestartableJenkinsRule`. The main benefit to `JenkinsSessionRule` is that `#then` runs immediately, so it plays nicely with things like `@After.`

Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/DownstreamFailureCause.java

When a downstream build fails, it's helpful to have a link to click on to navigate to that failed build to investigate.

Add hyperlink to failing downstream build

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/DownstreamFailureCause.java

See [JENKINS-66269](https://issues.jenkins.io/browse/JENKINS-66269). Reimplements #57 such that we leave `getShortDescription` alone but override `print` to add a hyperlink to the console.

[JENKINS-66269] jenkinsci/pipeline-build-step-plugin#57 precludes usage of the API

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

When `wait: true` is set, add a `WarningAction` to the build step `FlowNode` when the downstream build isn't successful even when `propagate: false` is also set.
Also, log the build result when the downstream run completes.
Implements https://issues.jenkins.io/browse/JENKINS-70623

Mark pipeline build step with the downstream build result

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerAction.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/help-waitForStart.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

Add a new option `waitForStart` to the `build` step. The `waitForStart` option changes the behavior of the `build` step to block until the downstream build is started and a valid `RunWrapper` can be returned.
Implements https://issues.jenkins.io/browse/JENKINS-60849

Implement option to wait only until the downstream build is started

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildAction.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildListener.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/Messages.properties
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStep/config.jelly
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStep/help-propagate.html
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStep/help-runId.html
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStep/help.html
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepTest.java

Add a new `waitForBuild` pipeline step that waits for a given build to complete. The build to wait on is defined by its [`externalizableId`](https://github.com/jenkinsci/jenkins/blob/62c2fbcc7af34a2bc4edd67e46939fbe90f3b899/core/src/main/java/hudson/model/Run.java#L2467).
Implements https://issues.jenkins.io/browse/JENKINS-70617.
This PR is intended to be paired with https://github.com/jenkinsci/pipeline-build-step-plugin/pull/105. The source branch is currently based off of https://github.com/stuartrowe/pipeline-build-step-plugin/tree/JENKINS-60849.

Implement waitForBuild step

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

Fix for https://issues.jenkins.io/browse/JENKINS-70844 which is a knock on from https://github.com/jenkinsci/pipeline-build-step-plugin/pull/107.
Looking at the implementation of `BuildCondition`s in declarative pipelines, any `WarningAction` attached to a node within a stage will trigger the `Unsuccessful` condition.  See [BuildCondition.java#L165](https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/a31cb3b80ef89014f1b4dc5a37ab514e470a3f94/pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java#L165).
In order to maintain the previous behavior, only add the `WarningAction` when `propagte: true`.

Only add WarningAction when propagate: true

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildListener.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepTest.java

Add a WarningAction to the `waitForBuild` step FlowNode when the downstream build isn't successful.
Also, log the build result when the downstream run completes.
This is the `waitForBuild` step equivalent of https://github.com/jenkinsci/pipeline-build-step-plugin/pull/107.
Implements https://issues.jenkins.io/browse/JENKINS-70983

Mark pipeline waitForBuild step with the downstream build result

---

src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep/config.jelly

See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I installed this plugin on a custom build of Jenkins that had Prototype ripped out (a local project branch), went to the Pipeline snippets page, selected the build …

Replace Prototype.js with native JavaScript

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java

As a result of https://github.com/jenkinsci/jenkins-test-harness/pull/198 we see occasionally flakes in PCT
```
java.io.IOException: …/pipeline-build-step-plugin/target/tmp/j h17881095753960446783/jobs/dir1/jobs/downstream/builds/1/build.xml
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:144)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(Temporar …
```

Make `BuildTriggerListener` wait for `onFinalized`, not just `onCompleted`

---

README.md

Currently, the code throws the error:
`java.lang.IllegalArgumentException: Expected named arguments but got`
`[parameter-name, credentials-id]` respectively `[parameter-name, secret-value]`
Fixing as suggested in this PR solves this problem.

README: Make parameters named

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildListener.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStep.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepExecution.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepTest.java

Implemented `stop()` method in `WaitForBuildStepExecution` so aborts can be propagated from the upstream job to downstream job that is being waited on.
Fix for https://issues.jenkins.io/browse/JENKINS-71961.
Add two new test cases to `WaitForBuildStepTest`:
- `abortBuild()`: validates that when the downstream job being waited on is aborted that the upstream job will be aborted too.
- `interruptFlow()`: validates that when the upstream job aborted then downstream job being waited on will be aborted too.
```[tasklist]
```

[JENKINS-71961] Fix waitForBuild Step does not abort downstream build when upstream job aborted

---

pom.xml
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/DownstreamBuildAction.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepRestartTest.java
src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

See https://github.com/jenkinsci/pipeline-build-step-plugin/pull/127#discussion_r1426716551.
CC @artmorse
```[tasklist]
```

Store `DownstreamBuildAction` on `Run` instead of `FlowNode` for consistent persistence even on completed builds

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java

When running with `-Dorg.jvnet.hudson.test.RemainingActivityListener.fatal=true` I got the following error (fixed in this PR):
```
[ERROR] org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerStepTest.waitForStart -- Time elapsed: 0.993 s <<< FAILURE!
java.lang.AssertionError: ds #1 still seems to be running, which could break deletion of log files or metadata
at org.jvnet.hudson.test.RemainingActivityListener.onTearDown(RemainingActivityListener.java:62)
at org.jvnet.hudson.test.JenkinsRule.after(JenkinsRule.java:502)
at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:677)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.lang.Thread.run(Thread.java:1583)
```

De-flake `BuildTriggerStepTest.waitForStart`

---

src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepTest.java

Explicitly wait for the "wait" semaphore in downstream build, allowing the downstream build to go through full initialization.
Otherwise in some case you'd run into a timing issue where downstream build is not aborted as expected.
```
10.218 [id=211]	WARNING	o.j.p.w.cps.CpsFlowExecution#saveOwner: Error persisting Run ds#1
java.nio.channels.ClosedByInterruptException
at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:171)
at java.base/sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:472)
at hudson.util.AtomicFileWriter.commit(AtomicFileWriter.java:234)
at hudson.XmlFile.write(XmlFile.java:221)
at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeBy …
```

Flakes in WaitForBuildStepTest

---

src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepExecution.java
src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepExecution.java
src/main/resources/org/jenkinsci/plugins/workflow/support/steps/build/Messages.properties

The label for the `build` step should differentiate between whether the step is waiting for the scheduled build to complete. Similarly the `waitForBuild` step label should reference the build it's waiting on.
Ran local pipelines that called `build` with a combination of `wait=true`, `wait=false` and `waitForStart=true` along with calling the `waitForBuild` step. Confirmed that labels associated with the step nodes was updated accordingly.

Update LabelAction messages for Build and WaitForBuild steps
